export const CHANGE_SEARCH_FIELD = 'changeSearchField';
export const RQUESTE_ROBOTS_PENDING = 'RQUESTE_ROBOTS_PENDING';
export const RQUESTE_ROBOTS_SUCCESS = 'RQUESTE_ROBOTS_SUCCESS';
export const RQUESTE_ROBOTS_FAILED = 'RQUESTE_ROBOTS_FAILED';